version: '3'

services:
  app:
    image: docker pull docker.pkg.github.com/silencesys/ffuk-vote/ffuk-vote-server:latest
    container_name: vote-server
    env_file:
      - .app.env
      - .db-oci.env
      - .db-mongo.env
    networks:
      - vote-net
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"
  nginx:
    image: nginx:alpine
    container_name: vote-nginx
    volumes:
      - ./development/configs/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - vote-net
    ports:
      - 22674:80
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"
  client:
    image: docker.pkg.github.com/silencesys/ffuk-vote/ffuk-vote-client:client
    container_name: vote-client
    networks:
      - vote-net
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"
  mongodb:
    image: mongo
    container_name: vote-mongodb
    env_file:
      - .db-mongo.env
    volumes:
      - vote-mongo:/data/db
    ports:
      - 27072:27017
    networks:
      - vote-net
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"


volumes:
  vote-mongo:
    driver: local

networks:
  vote-net:
    driver: bridge