name: 'Build Docker image: Client'

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [ push, release ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      uses: docker/build-push-action@v1.0.1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.pkg.github.com
        repository: silencesys/ffuk/vote-client
        tags: latest
        tag_with_ref: true
